config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :update, :edit] do
  end

  resources :events, only: [:new, :create, :show, :destroy] do
    resources :bookings, only: :create
  end
  resources :bookings, only: [:update, :destroy] do
    resources :messages, only: [:index, :create]
    resources :reviews, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :event
  belongs_to :user
  has_one :review, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :title, presence: true
  validates :date, presence: true
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :location_changed?
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :booking
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  has_many :bookings
  has_many :reviews, through: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :description, presence: true, if: :status

  mount_uploader :photo, PhotoUploader

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  def pending_reviews# return past bookings, accepted without reviews
    pending_reviews = []
    @past_events =self.events.select { |event| event.date < Time.now }
    @past_events.each do |event|
      event.bookings.each { |booking| pending_reviews << booking if booking.status == "accepted" && booking.review.nil? }
    end
    return pending_reviews
  end

  def all_bookings
    bookings = []
    self.bookings.each do |b|
      bookings << b
    end
    self.events.each do |e|
      e.bookings.each do |b|
        bookings << b
      end
    end
    return bookings
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index , unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :photo, :status, :location, :tarif])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @user = User.find(params[:user_id])
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.status = "pending"
    @booking.price = @user.tarif
    @booking.save
    redirect_to event_path(@event)
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.js
    end

  end

  private

  def booking_params
    params.permit(:event_id, :user_id, :status)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])
    @booking = Booking.new
    @bookings = @event.bookings
    @iduser_booked = @bookings.map { |booking| booking.user.id }
    @users = User.where(status: true).where.not(id: @iduser_booked.push(@event.user_id)).near(@event.location, 100)
    authorize @event

    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude#,
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end
  end

  def new
    @event = Event.new
    authorize @event
  end

  def create
    @pleureurs = User.where(status: true)
    @event = Event.new(event_params)
    @event.user = current_user
    authorize @event
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @user = @event.user
    authorize @event
    @event.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@user) }
      format.js
    end

  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @booking = Booking.find(params[:booking_id])
    @user = current_user
    @messages = policy_scope(Message).order(created_at: :desc).where(booking: @booking)
    @message = Message.new
    @bookings = @user.all_bookings
  end

  def create
    @message = Message.new(message_params)
    @booking = Booking.find(params[:booking_id])
    @user = current_user
    @message.booking = @booking
    @message.user = @user
    authorize @message
    @message.save
    redirect_to booking_messages_path(@booking)
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action  :authenticate_user!, only: :home
  def home
    !current_user.nil? ? @id = current_user.id : @id = 0
    if params[:query].present?
      @users = User.where(status: true).where.not(id: @id).near(params[:query], 100)
    else
      @users = User.where("status = ? AND id != ?", true, @id)
    end

    respond_to do |format|
      format.html { render 'home' }
      format.js
    end

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

def create
  @review = Review.new(review_params)
  @review.booking = Booking.find(params[:booking_id])
  @user = @review.booking.event.user
  authorize @review
  if @review.save
    redirect_to user_path(@user)
  else
    redirect_to user_path(@user)
  end
end

private

def review_params
   params.require(:review).permit(:content, :rating)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @events = @user.events
    @bookings = @user.bookings
    @reviews = @user.reviews
    @pending_reviews = @user.pending_reviews
    authorize @user
    @users = User.where.not(latitude: nil, longitude: nil)
    #needed for creating review
    @review = Review.new

  end

  def edit
    authorize @user
  end

  def update
    @user.status = params[:user][:status] == "1"
    @user.update(user_params)
    redirect_to user_path(@user)
    authorize @user
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description, :phone_number, :photo, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/destroy.js.erb
document.getElementById('bk-<%=@booking.id%>').remove();

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <%= simple_form_for [@event, @booking] do |f| %>
        <%= hidden_field_tag(:user_id, @user.id) %>
        <%= hidden_field_tag(:event_id, @event.id) %>
        <%= f.label "Send a message to #{@user.first_name} with your booking" %>
        <%= f.input :description, label: false %>
        <%= f.submit "send a request", class: "btn btn-success", style: "width: 100%" %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/_show_available_weepers.html.erb
<div class="event-show-bookings">
  <%if not @users.first.nil?  %>
  <h4 class="text-center">Available weepers around you</h4>
      <div class="row">

        <% @users.each do |user|%>

          <div class="col-xs-6 col-sm-4">

            <%= link_to user_path(user, event_id: @event) do %>
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= user.photo? ? (cl_image_path user.photo) : ('https://picsum.photos/g/200/300') %>');">
                <div class="card-description">
                  <h2><%= user.first_name.capitalize %></h2>
                  <p><%= user.tarif %> € </p>
                </div>
              </div>
            <% end %>

            <div class="text-center">
              <%= link_to event_bookings_path(@event, user_id: user.id), method: :post do %>
                <div class="btn btn-success" style="width: 100%">Send a request</div>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>
  <% else  %>
    <h4 class="text-center">There are no weepers available around you</h4>
  <% end %>
</div>

app/views/events/_show_bookings.html.erb
<%if not @bookings.first.nil?  %>
<div class="event-show-bookings">
  <h4 class="text-center">Your current bookings</h4>
      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-xs-6 col-sm-4">
            <div class="booking-card">
              <%= link_to user_path(booking.user) do %>
                <div class="card small" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= booking.user.photo? ? (cl_image_path booking.user.photo) : ('https://picsum.photos/g/100/100') %>');">
                  <div class="card-description">
                    <h2><%= booking.user.first_name.capitalize %></h2>
                    <p><%= booking.user.tarif %> € </p>
                  </div>
                </div>
                <% if booking.status == "pending" %>
                  <div class="btn btn-primary text-center pending-status" style="width: 100%;">Status: <%= booking.status %></div>
                <% elsif booking.status == "declined" %>
                  <div class="btn btn-danger text-center pending-status" style="width: 100%;">Status: <%= booking.status %></div>
                <% else  %>
                  <div class="btn btn-success text-center pending-status" style="width: 100%;">Status: <%= booking.status %></div>
                <% end %>
              <% end %>
            </div>
            <div class="text-center">
              <%= link_to "Send a message", booking_messages_path(booking), class: 'link-send-message' %>
            </div>
          </div>
        <% end %>
      </div>
</div>
<% end %>

app/views/events/destroy.js.erb
document.getElementById('ev-<%=@event.id%>').remove();

app/views/events/new.html.erb
<!-- simple form pour affiche lieu, date, titre  -->

<div class="wrap img-cover">
  <div class= "container form-box">
    <div class= "row">
      <div class= "col-xs-12 form">
      <div class="text-center"><img src="http://moziru.com/images/purple-rose-clipart-png-tumblr-10.png" style="max-width: 150px; max-height: auto;" /> </div>
      <h2 class= "text-center" style="padding-bottom: 50px; font-weight: bolder; font-size: 40px;">Create an event</h2>
      <%= simple_form_for [@event] do |f| %>
        <%= f.input :title, label: false, placeholder: "Event title" %>
        <%= f.input :location, label: false, placeholder: "Event location" %>
        <%= f.input :date, as: :string, input_html: { class: "datepicker" }, label: false, placeholder: "Event date" %>
        <div class= "text-center margin_top">
          <% if policy(Event).create? %>
        <%= f.submit "R.I.P", class:"btn-medium" %>
        <% end %>
        </div>
      <% end %>
      </div>
    </div>
  </div>

</div>

app/views/events/show.html.erb
 <div class="container">
    <div class="row">
      <div class="col-xs-6-col-xs-offset-3 ">
        <h1 class="yourevent text-center"><%= @event.title %></h1>
          <p class="title text-center";><em>On <%= @event.date.strftime('%A, %b %d') %>, at <%= @event.location %></em> </p>
      </div>
    </div>
    <div class="main_container" style="display: flex;">
        <div class="col-xs-12 col-md-8">
        <!-- Part 1 display sweeper already booked or request send  -->
          <%= render 'show_bookings' %>

        <!-- Part 2 display sweeper available, build forms to create a booking -->
          <%= render 'show_available_weepers' %>
        </div>


        <div
          id="map"
          class="hidden-xs col-md-4"
          style="
          height: 100vh;
          margin-top: 20px;
          box-shadow: 0px 5px 5px grey;"
          data-markers="<%= @markers.to_json %>"
        ></div>
    </div>
  </div>


  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cry me a river</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div style="min-height: 100vh;">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/messages/_inbox.html.erb
<div class="bookings">
  <% @bookings.each do |b| %>
    <%= link_to booking_messages_path(b) do %>
      <% if @booking == b %>
        <div class="message-inbox-active">
          <div class="avatar">
            <%= cl_image_tag(b.user.photo, class: "avatar")%>
          </div>
          <div class="message-name">
            <h3><%= b.user.first_name %> <%= b.user.last_name %></h3>
            <p><%= b.event.date %></p>
          </div>
          <div class="message-body">
            <p><strong><%= b.event.title %></strong></p>
          </div>
        </div>
      <% else %>
          <div class="message-inbox">
            <div class="avatar">
              <%= cl_image_tag(b.user.photo, class: "avatar")%>
            </div>
            <div class="message-name">
              <h3><%= b.user.first_name %> <%= b.user.last_name %></h3>
              <p><%= b.event.date %></p>
            </div>
            <div class="message-body">
              <p><strong><%= b.event.title %></strong></p>
            </div>
          </div>
        <% end %>
    <% end %>
  <% end %>
</div>

app/views/messages/_message_list.html.erb
<div class="message-list">
  <% @messages.reverse.each do |m| %>
    <div class="inbox-list">
      <% if m.user == current_user %>
        <div class="message-text margin-right">
          <%= m.content %>
        </div>
        <div class="message-sender-avatar">
          <%= cl_image_tag(m.user.photo, class:' message-sender-avatar')%>
        </div>
      <% else %>
        <div class="message-sender-avatar">
          <%= cl_image_tag(m.user.photo, class:' message-sender-avatar')%>
        </div>
        <div class="message-text">
          <%= m.content %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<div class="message-form-box">
  <%= simple_form_for [@booking, @message] do |f| %>
  <%= hidden_field_tag(:user_id, @user.id) %>
  <%= f.input :content, label: false %>
  <%= f.submit "send message", class: "btn btn-success", style: "width: 100%" %>
  <% end %>
</div>

app/views/messages/index.html.erb
<div class="message-wrapper" style="padding:20px">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-4">
        <%= render "inbox" %>

      </div>
      <div class="col-xs-8">
        <%=  render "message_list" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/_user_profiles.html.erb
<div class="container">
    <div class="row">
    <% @users.each do |user| %>
      <div class="col-xs-12 col-sm-4 col-md-3">
        <%= link_to user_path(user.id) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= user.photo? ? (cl_image_path user.photo) : ('https://picsum.photos/g/200/300') %>');">
            <div class="card-description">
              <h2><%= user.first_name.capitalize %></h2>
              <p><%= user.tarif %> € </p>
            </div>
          </div>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container">
  <div class="row">
    <h3>Find a weeper close to you</h3>
    <%= form_tag(root_path, method: :get, remote: true) do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Try 'Paris'"
      %>
    <% end %>
  </div>
</div>



<!-- all users -->
<div id="wrapper">
  <%= render 'user_profiles' %>
</div>

app/views/pages/home.js.erb
if (typeof(userProfiles) === 'undefined') {
  var usersProfiles = document.getElementById('wrapper');
}


usersProfiles.innerHTML = "<%= j render 'user_profiles', users: @users %>";

app/views/shared/_audioplayer.html.erb
<div class="player">
  <audio src ="" controls id="audioPlayer">
    Sorry, your browser doesn't support html5!
  </audio>
    <ul class="hidden" id="playlist">
      <li class="current-song" id="audioControl"><a href="http://res.cloudinary.com/dfjd5sbad/video/upload/v1512040826/funebre_1_kaaybj.mp3">Marche funebre</a></li>
      <li><a href="http://res.cloudinary.com/dfjd5sbad/video/upload/v1512041324/Musique_Militaire_-_Sonnerie_aux_morts_Ame%CC%81ricaine_bqimyy.mp3">Marche militaire</a></li>
      <li><a href="http://res.cloudinary.com/dfjd5sbad/video/upload/v1512049132/Jeff_Buckley_-_Hallelujah_fron5e.mp3">Hallelujah</a></li>
    </ul>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'enterrement.jpg' %>');">
  <%= render 'shared/audioplayer' %>
  <div class="banner-content">
    <h1>Cry me a river</h1>
      <p>
      <span id="banner-typed-text"></span>
      </p>
      <% if policy(Event).new? %>
        <%= link_to new_event_path, class:"btn btn-primary btn-lg" do %>
        Create an event !
      <% end %>
      <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"> never too late for a selfie </i></a>
    <a href="#"><i class="fa fa-twitter"> unlimited sadness (140 char max) </i></a>
  </div>
  <div class="footer-copyright">
    Footer made with <i class="fa fa-heart"></i> @ Pere Lachaise
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
    <% if !current_user.all_bookings.empty? %>
      <%= link_to "Messages", booking_messages_path(current_user.all_bookings.first), class: "navbar-wagon-item navbar-wagon-link"%>
    <% end %>




      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <%= cl_image_tag(current_user.photo,
      width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" ) %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <% if policy(current_user).show? %>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

</div>

app/views/users/_edit_user_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <%= simple_form_for(@user) do |f| %>
      <%= f.input :first_name, autofocus: true %>
      <%= f.input :last_name %>
      <%= f.label :status, "Etes vous un pleureur ?" %>
      <%= f.check_box :status %>
      <div class="toto" id="hiddenfield">
        <%= f.input :description, required: true %>
        <%= f.input :tarif, required: :true %>
        <%= f.input :location, required: :true %>
      </div>
      <%= f.input :description %>
      <%= f.input :phone_number %>
      <%= f.input :tarif %>
      <%= f.input :location %>
      <%= f.submit "Update profile" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_profile_event_list.html.erb
<div class="events">
  <% if @events.empty?  %>
    <%= link_to new_event_path do %>
    <div class="flex text-center">
      <i class="fa fa-plus fa-bg" aria-hidden="true">  Create an event</i>
    </div>
    <% end %>
  <% else %>
  <p class="title text-center">All your events</p>

    <% @events.each do |e| %>

      <div class="event-card" id="ev-<%=e.id%>" >

          <div class="event-description">
            <div class="event-title">
              <h3><%= e.title %></h3>
            </div>
            <div class="event-date">
              <p><%= e.date %></p>
            </div>
            <div class="event-location">
             <p><%= e.location %></p>
            </div>
            <%= link_to event_path(e), method: :delete, remote: true do %>
              <i class="fa fa-times fa-bg status declined hover" aria-hidden="true"></i>
            <% end %>
          </div>

          <div class="event-bookings">

            <% e.bookings.each do |b| %>

             <div class="message" id="bk-<%=b.id%>">
                  <div class="avatar">
                    <%= cl_image_tag(b.user.photo, class: "avatar")%>
                  </div>
                  <div class="message-name">
                    <h3><%= b.user.first_name %> <%= b.user.last_name %></h3>
                    <p><%= e.date %></p>
                  </div>
                  <div class="message-body">
                    <p>
                      <% if !b.messages.empty? %>
                        <%= b.messages.last.content %>
                        <% else %>
                        <p><em>No messages sent yet</em></p>
                      <% end %>
                    </p>
                  </div>
                    <div class="message-status">
                      <p class="status <%= b.status %>"><%= b.status %></p>
                      <p class="price"><%= b.price %>€</p>
                    </div>
                  <div class="message-actions">

                    <%= link_to booking_path(b), method: :delete , remote: true do %>
                      <i class="fa fa-times fa-bg status declined hover" aria-hidden="true"></i>
                    <% end %>

                  </div>
                </div>


            <% end %>

              <%= link_to event_path(e) do %>
              <div class="add-booking text-center">
                <i class="fa fa-plus fa-bg" aria-hidden="true">  Book another weeper</i>
              </div>
              <% end %>


          </div>

      </div>

    <% end %>

  <% end %>

</div>

app/views/users/_profile_pendingreview_list.html.erb
<div class="pending_review">
  <p class="title text-center">Add a review</p>

  <% @pending_reviews.each do |booking| %>

    <%= simple_form_for [booking, @review] do |f| %>
    <div class="review">
       <div class="text-center">
          <h3><%= booking.event.title %> on <%= booking.event.date.strftime("%A, %b %d") %></h3>
       </div>
      <div class="review-top">
        <div class="review-who">
          <%= cl_image_tag(booking.user.photo, crop: :fill , class: "avatar") %>
          <h3> <%= booking.user.first_name %></h3>
        </div>
        <div class="review-rating">
          <%= f.input :rating, collection: 0..5,  label: false, prompt: "Rating" %>
        </div>
      </div>

      <div class="review-bottom">
        <div class="review-content">
          <%= f.input :content,  label: false, placeholder: 'Here for your review'%>
        </div>
      </div>
      <div class="review-button text-center">
        <%= f.submit '+ Add your review', :class => 'btn btn-review'  %>
      </div>
    </div>
      <% end %>
  <% end %>
</div>

app/views/users/_profile_user_information.html.erb
<div class="user_information">
  <% if policy(@user).edit? %>
    <%= link_to edit_user_path(@user) do %>
      <i class="fa fa-pencil" aria-hidden="true"></i>
    <% end %>
  <% end %>
  <div class="flex">
    <div class="avatar">
      <%= cl_image_tag(@user.photo,   class: "avatar dropdown-toggle")%>
    </div>
  </div>
  <div class="information">
    <ul class="list-unstyled">
      <li class="name"><%= @user.first_name %> <%= @user.last_name %></li>
      <li class="details"><%= @user.email %></li>
      <li class="details"><%= @user.phone_number %></li>
      <li class="details"><%= @user.location %></li>
      <% if @user.tarif %>
        <li class="details">price: <%= @user.tarif %>€</li>
      <% end %>
    </ul>
  </div>
  <div class="description">
    <p class="title">Description</p>
    <p><%= @user.description %></p>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'edit_user_form' %>

app/views/users/show.html.erb
<div class="container user-profile-content">
  <div class="row">

    <% if policy(@user).edit? %> <!-- your profil  -->
      <div class="col-md-4">
        <%= render 'users/profile_user_information' %>
        <% if !@pending_reviews.first.nil? %>
          <%= render 'users/profile_pendingreview_list' %>
        <% end %>
      </div>

      <div class="col-md-8">
        <%= render 'users/profile_event_list' %>

        <% if !@bookings.empty?  %>
          <%= render 'users/profile_booking_list' %>
        <% end %>

        <% if !@reviews.first.nil? %>
          <%= render 'users/profile_review_list' %>
        <% end %>
      </div>

      <% elsif !@reviews.first.nil? %> <!--  profil weeper with reviews  -->
        <div class="col-md-4">
          <%= render 'users/profile_user_information' %>
        </div>

        <div class="col-md-8">
          <% if !@reviews.first.nil? %>
            <%= render 'users/profile_review_list' %>
          <% end %>
        </div>

      <% else %> <!--  profil weeper without reviews  -->

      <div class="col-md-6 col-md-offset-3">
        <%= render 'users/profile_user_information' %>

        <% if !@event.nil? %>
          <div class="text-center">
            <%= link_to event_bookings_path(@event, user_id: @user.id), method: :post do %>
              <div class="btn btn-success" style="width: 100%">Send a request</div>
            <% end %>
          </div>
        <% end %>
      </div>

    <% end %>

  </div>
</div>